[project]
name = "lazysleeper"
version = "0.1.0"
description = "LazySleeper is an app to analyze your sleep - just send me screenshots from your trackers like Haylouu app, Amazfit, Sleep as Android where I can see Deep Sleep, REM, waking up and falling asleep time and that's all!"
authors = [
    {name = "Silletr",email = "silletrMain@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "tesseract (>=0.1.3,<0.2.0)",
    "opencv-python (>=5.0.0.93,<6.0.0.0)",
    "pytesseract (>=0.3.13,<0.4.0)",
    "pillow (>=12.3.0,<13.0.0)",
    "pandas (>=3.0.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
